name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    env:
      SCW_ACCESS_KEY: ${{ secrets.SCALEWAY_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCALEWAY_SECRET_KEY }}
      SCW_PROJECT_ID: ${{ secrets.SCALEWAY_PROJECT_ID }}
      SCW_DEFAULT_REGION: ${{ secrets.SCALEWAY_REGION }}
      TF_VAR_project_id: ${{ secrets.SCALEWAY_PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="project_id=${{ secrets.SCALEWAY_PROJECT_ID }}" \
            -out=tfplan

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

      - name: Download tfplan artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/download-artifact@v3
        with:
          name: tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
